"""tournaments after add imports to env.py

Revision ID: 477b80ebe329
Revises: 76c22daf3d17
Create Date: 2025-05-08 23:31:39.991595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '477b80ebe329'
down_revision: Union[str, None] = '76c22daf3d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('current_stage', sa.String(), nullable=False),
    sa.Column('stage_deadline', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("type IN ('sets', 'minifigures')"),
    sa.PrimaryKeyConstraint('tournament_id')
    )
    op.create_table('tournament_participants',
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('minifigure_id', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('(set_id IS NOT NULL AND minifigure_id IS NULL) OR (set_id IS NULL AND minifigure_id IS NOT NULL)'),
    sa.ForeignKeyConstraint(['minifigure_id'], ['minifigures.minifigure_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_id'], ['sets.set_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.tournament_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('participant_id'),
    sa.UniqueConstraint('tournament_id', 'set_id', 'minifigure_id')
    )
    op.create_table('tournament_pairs',
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('participant1_id', sa.Integer(), nullable=False),
    sa.Column('participant2_id', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participant1_id'], ['tournament_participants.participant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant2_id'], ['tournament_participants.participant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.tournament_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_id'], ['tournament_participants.participant_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('pair_id'),
    sa.UniqueConstraint('tournament_id', 'stage', 'participant1_id', 'participant2_id')
    )
    op.create_table('tournament_votes',
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(36), nullable=False),
    sa.Column('voted_for', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pair_id'], ['tournament_pairs.pair_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voted_for'], ['tournament_participants.participant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vote_id'),
    sa.UniqueConstraint('pair_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_votes')
    op.drop_table('tournament_pairs')
    op.drop_table('tournament_participants')
    op.drop_table('tournaments')
    # ### end Alembic commands ###
