"""Create tournament winners table

Revision ID: 5e0a1434d99c
Revises: 9e048f8160e6
Create Date: 2025-05-15 12:43:23.135979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e0a1434d99c'
down_revision: Union[str, None] = '9e048f8160e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_winners',
    sa.Column('winner_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('minifigure_id', sa.String(), nullable=True),
    sa.Column('total_votes', sa.Integer(), nullable=True),
    sa.Column('won_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(set_id IS NOT NULL AND minifigure_id IS NULL) OR (set_id IS NULL AND minifigure_id IS NOT NULL)'),
    sa.ForeignKeyConstraint(['minifigure_id'], ['minifigures.minifigure_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_id'], ['sets.set_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.tournament_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('winner_id'),
    sa.UniqueConstraint('tournament_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_winners',
    sa.Column('winner_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tournament_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('set_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('minifigure_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_votes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('won_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint('set_id IS NOT NULL AND minifigure_id IS NULL OR set_id IS NULL AND minifigure_id IS NOT NULL', name='tournament_winners_check'),
    sa.ForeignKeyConstraint(['minifigure_id'], ['minifigures.minifigure_id'], name='tournament_winners_minifigure_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_id'], ['sets.set_id'], name='tournament_winners_set_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.tournament_id'], name='tournament_winners_tournament_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('winner_id', name='tournament_winners_pkey'),
    sa.UniqueConstraint('tournament_id', name='tournament_winners_tournament_id_key')
    )
    # ### end Alembic commands ###
