"""Add cascade delete to set_tags and minifigure_tags relationships

Revision ID: 9dca17455c2a
Revises: a96673864b7a
Create Date: 2025-04-28 22:21:40.023575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dca17455c2a'
down_revision: Union[str, None] = 'a96673864b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('minifigure_tags_tag_id_fkey', 'minifigure_tags', type_='foreignkey')
    op.drop_constraint('minifigure_tags_minifigure_id_fkey', 'minifigure_tags', type_='foreignkey')
    op.create_foreign_key(None, 'minifigure_tags', 'tags', ['tag_id'], ['tag_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'minifigure_tags', 'minifigures', ['minifigure_id'], ['minifigure_id'], ondelete='CASCADE')
    op.drop_constraint('photos_minifigure_id_fkey', 'photos', type_='foreignkey')
    op.drop_constraint('photos_set_id_fkey', 'photos', type_='foreignkey')
    op.create_foreign_key(None, 'photos', 'minifigures', ['minifigure_id'], ['minifigure_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'photos', 'sets', ['set_id'], ['set_id'], ondelete='CASCADE')
    op.drop_constraint('set_tags_tag_id_fkey', 'set_tags', type_='foreignkey')
    op.drop_constraint('set_tags_set_id_fkey', 'set_tags', type_='foreignkey')
    op.create_foreign_key(None, 'set_tags', 'sets', ['set_id'], ['set_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'set_tags', 'tags', ['tag_id'], ['tag_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'set_tags', type_='foreignkey')
    op.drop_constraint(None, 'set_tags', type_='foreignkey')
    op.create_foreign_key('set_tags_set_id_fkey', 'set_tags', 'sets', ['set_id'], ['set_id'])
    op.create_foreign_key('set_tags_tag_id_fkey', 'set_tags', 'tags', ['tag_id'], ['tag_id'])
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.create_foreign_key('photos_set_id_fkey', 'photos', 'sets', ['set_id'], ['set_id'])
    op.create_foreign_key('photos_minifigure_id_fkey', 'photos', 'minifigures', ['minifigure_id'], ['minifigure_id'])
    op.drop_constraint(None, 'minifigure_tags', type_='foreignkey')
    op.drop_constraint(None, 'minifigure_tags', type_='foreignkey')
    op.create_foreign_key('minifigure_tags_minifigure_id_fkey', 'minifigure_tags', 'minifigures', ['minifigure_id'], ['minifigure_id'])
    op.create_foreign_key('minifigure_tags_tag_id_fkey', 'minifigure_tags', 'tags', ['tag_id'], ['tag_id'])
    # ### end Alembic commands ###
