"""Add price to Minifigure

Revision ID: a96673864b7a
Revises: aab5b9d28067
Create Date: 2025-04-28 16:45:36.118593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a96673864b7a'
down_revision: Union[str, None] = 'aab5b9d28067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('minifigures', sa.Column('price', sa.Integer(), nullable=True))
    op.drop_constraint('fk_minifigures_face_photo_id', 'minifigures', type_='foreignkey')
    op.create_foreign_key(None, 'minifigures', 'photos', ['face_photo_id'], ['photo_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'minifigures', type_='foreignkey')
    op.create_foreign_key('fk_minifigures_face_photo_id', 'minifigures', 'photos', ['face_photo_id'], ['photo_id'])
    op.drop_column('minifigures', 'price')
    # ### end Alembic commands ###
