"""Fix relationship models

Revision ID: aab5b9d28067
Revises: 07ff5aa6091f
Create Date: 2025-04-20 13:32:34.663388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aab5b9d28067'
down_revision: Union[str, None] = '07ff5aa6091f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'is_main',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'is_main',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
